id = "tokyo-night-storm"
name = "Tokyo Night Storm Theme"
description = "A Tokyo Night style theme."
version = "0.0.1"
schema_version = 1
authors = ["Jason Lee <166997982@qq.com>"]
repository = "https://github.com/ZeroHawkeye/TokyoNightStoreTheme/tree/main"
